[tool.poetry]
name = "bfs"
version = "0.1.0"
description = "A non-trivial Python DevOps project, implementing search through a grid map."
authors = ["Brandon Corfman <bcorfman@fastmail.fm>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
flake8 = "^6.0.0"
yapf = "^0.32.0"
ipython = "^8.8.0"
coverage = "^7.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
