name: Python build and test

on: [push]

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: make install PYTHON_VERSION=3.10
      - name: Lint with Pylint
        run: make lint
      - name: Test with Pytest
        run: make test

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          make cloudinstall PYTHON_VERSION=3.10
      - name: Test with Pytest
        run: |
          make cloudtest
