name: Test Streamlit Cloud deployment
on: 
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

env:
  STREAMLIT_DEPLOYMENT_URL: "https://bcorfman-bfs-main-ihgp7e.streamlit.app"

jobs:
  test:
    runs-on: ubuntu-latest
    container: bcorfman/streamlit-docker
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Install browsers for system testing with Playwright
        run: |
          poetry run playwright install-deps
          poetry run playwright install
      - name: Test with pytest
        run: |
          poetry run pytest -m system
