name: Test Streamlit Cloud deployment
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright/python:v1.34.0-jammy
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Delay to allow Streamlit Cloud to update
        run: sleep 100
      - name: Test with pytest
        run: poetry run pytest --cov-branch --cov-report lcov --cov=core tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
